package dev.cryptospace.anvil.core.input

import org.lwjgl.glfw.GLFW.GLFW_KEY_0
import org.lwjgl.glfw.GLFW.GLFW_KEY_1
import org.lwjgl.glfw.GLFW.GLFW_KEY_2
import org.lwjgl.glfw.GLFW.GLFW_KEY_3
import org.lwjgl.glfw.GLFW.GLFW_KEY_4
import org.lwjgl.glfw.GLFW.GLFW_KEY_5
import org.lwjgl.glfw.GLFW.GLFW_KEY_6
import org.lwjgl.glfw.GLFW.GLFW_KEY_7
import org.lwjgl.glfw.GLFW.GLFW_KEY_8
import org.lwjgl.glfw.GLFW.GLFW_KEY_9
import org.lwjgl.glfw.GLFW.GLFW_KEY_A
import org.lwjgl.glfw.GLFW.GLFW_KEY_APOSTROPHE
import org.lwjgl.glfw.GLFW.GLFW_KEY_B
import org.lwjgl.glfw.GLFW.GLFW_KEY_BACKSLASH
import org.lwjgl.glfw.GLFW.GLFW_KEY_BACKSPACE
import org.lwjgl.glfw.GLFW.GLFW_KEY_C
import org.lwjgl.glfw.GLFW.GLFW_KEY_CAPS_LOCK
import org.lwjgl.glfw.GLFW.GLFW_KEY_COMMA
import org.lwjgl.glfw.GLFW.GLFW_KEY_D
import org.lwjgl.glfw.GLFW.GLFW_KEY_DELETE
import org.lwjgl.glfw.GLFW.GLFW_KEY_DOWN
import org.lwjgl.glfw.GLFW.GLFW_KEY_E
import org.lwjgl.glfw.GLFW.GLFW_KEY_END
import org.lwjgl.glfw.GLFW.GLFW_KEY_ENTER
import org.lwjgl.glfw.GLFW.GLFW_KEY_EQUAL
import org.lwjgl.glfw.GLFW.GLFW_KEY_ESCAPE
import org.lwjgl.glfw.GLFW.GLFW_KEY_F
import org.lwjgl.glfw.GLFW.GLFW_KEY_F1
import org.lwjgl.glfw.GLFW.GLFW_KEY_F10
import org.lwjgl.glfw.GLFW.GLFW_KEY_F11
import org.lwjgl.glfw.GLFW.GLFW_KEY_F12
import org.lwjgl.glfw.GLFW.GLFW_KEY_F13
import org.lwjgl.glfw.GLFW.GLFW_KEY_F14
import org.lwjgl.glfw.GLFW.GLFW_KEY_F15
import org.lwjgl.glfw.GLFW.GLFW_KEY_F16
import org.lwjgl.glfw.GLFW.GLFW_KEY_F17
import org.lwjgl.glfw.GLFW.GLFW_KEY_F18
import org.lwjgl.glfw.GLFW.GLFW_KEY_F19
import org.lwjgl.glfw.GLFW.GLFW_KEY_F2
import org.lwjgl.glfw.GLFW.GLFW_KEY_F20
import org.lwjgl.glfw.GLFW.GLFW_KEY_F21
import org.lwjgl.glfw.GLFW.GLFW_KEY_F22
import org.lwjgl.glfw.GLFW.GLFW_KEY_F23
import org.lwjgl.glfw.GLFW.GLFW_KEY_F24
import org.lwjgl.glfw.GLFW.GLFW_KEY_F25
import org.lwjgl.glfw.GLFW.GLFW_KEY_F3
import org.lwjgl.glfw.GLFW.GLFW_KEY_F4
import org.lwjgl.glfw.GLFW.GLFW_KEY_F5
import org.lwjgl.glfw.GLFW.GLFW_KEY_F6
import org.lwjgl.glfw.GLFW.GLFW_KEY_F7
import org.lwjgl.glfw.GLFW.GLFW_KEY_F8
import org.lwjgl.glfw.GLFW.GLFW_KEY_F9
import org.lwjgl.glfw.GLFW.GLFW_KEY_G
import org.lwjgl.glfw.GLFW.GLFW_KEY_GRAVE_ACCENT
import org.lwjgl.glfw.GLFW.GLFW_KEY_H
import org.lwjgl.glfw.GLFW.GLFW_KEY_HOME
import org.lwjgl.glfw.GLFW.GLFW_KEY_I
import org.lwjgl.glfw.GLFW.GLFW_KEY_INSERT
import org.lwjgl.glfw.GLFW.GLFW_KEY_J
import org.lwjgl.glfw.GLFW.GLFW_KEY_K
import org.lwjgl.glfw.GLFW.GLFW_KEY_KP_0
import org.lwjgl.glfw.GLFW.GLFW_KEY_KP_1
import org.lwjgl.glfw.GLFW.GLFW_KEY_KP_2
import org.lwjgl.glfw.GLFW.GLFW_KEY_KP_3
import org.lwjgl.glfw.GLFW.GLFW_KEY_KP_4
import org.lwjgl.glfw.GLFW.GLFW_KEY_KP_5
import org.lwjgl.glfw.GLFW.GLFW_KEY_KP_6
import org.lwjgl.glfw.GLFW.GLFW_KEY_KP_7
import org.lwjgl.glfw.GLFW.GLFW_KEY_KP_8
import org.lwjgl.glfw.GLFW.GLFW_KEY_KP_9
import org.lwjgl.glfw.GLFW.GLFW_KEY_KP_ADD
import org.lwjgl.glfw.GLFW.GLFW_KEY_KP_DECIMAL
import org.lwjgl.glfw.GLFW.GLFW_KEY_KP_DIVIDE
import org.lwjgl.glfw.GLFW.GLFW_KEY_KP_ENTER
import org.lwjgl.glfw.GLFW.GLFW_KEY_KP_EQUAL
import org.lwjgl.glfw.GLFW.GLFW_KEY_KP_MULTIPLY
import org.lwjgl.glfw.GLFW.GLFW_KEY_KP_SUBTRACT
import org.lwjgl.glfw.GLFW.GLFW_KEY_L
import org.lwjgl.glfw.GLFW.GLFW_KEY_LEFT
import org.lwjgl.glfw.GLFW.GLFW_KEY_LEFT_ALT
import org.lwjgl.glfw.GLFW.GLFW_KEY_LEFT_BRACKET
import org.lwjgl.glfw.GLFW.GLFW_KEY_LEFT_CONTROL
import org.lwjgl.glfw.GLFW.GLFW_KEY_LEFT_SHIFT
import org.lwjgl.glfw.GLFW.GLFW_KEY_LEFT_SUPER
import org.lwjgl.glfw.GLFW.GLFW_KEY_M
import org.lwjgl.glfw.GLFW.GLFW_KEY_MENU
import org.lwjgl.glfw.GLFW.GLFW_KEY_MINUS
import org.lwjgl.glfw.GLFW.GLFW_KEY_N
import org.lwjgl.glfw.GLFW.GLFW_KEY_NUM_LOCK
import org.lwjgl.glfw.GLFW.GLFW_KEY_O
import org.lwjgl.glfw.GLFW.GLFW_KEY_P
import org.lwjgl.glfw.GLFW.GLFW_KEY_PAGE_DOWN
import org.lwjgl.glfw.GLFW.GLFW_KEY_PAGE_UP
import org.lwjgl.glfw.GLFW.GLFW_KEY_PAUSE
import org.lwjgl.glfw.GLFW.GLFW_KEY_PERIOD
import org.lwjgl.glfw.GLFW.GLFW_KEY_PRINT_SCREEN
import org.lwjgl.glfw.GLFW.GLFW_KEY_Q
import org.lwjgl.glfw.GLFW.GLFW_KEY_R
import org.lwjgl.glfw.GLFW.GLFW_KEY_RIGHT
import org.lwjgl.glfw.GLFW.GLFW_KEY_RIGHT_ALT
import org.lwjgl.glfw.GLFW.GLFW_KEY_RIGHT_BRACKET
import org.lwjgl.glfw.GLFW.GLFW_KEY_RIGHT_CONTROL
import org.lwjgl.glfw.GLFW.GLFW_KEY_RIGHT_SHIFT
import org.lwjgl.glfw.GLFW.GLFW_KEY_RIGHT_SUPER
import org.lwjgl.glfw.GLFW.GLFW_KEY_S
import org.lwjgl.glfw.GLFW.GLFW_KEY_SCROLL_LOCK
import org.lwjgl.glfw.GLFW.GLFW_KEY_SEMICOLON
import org.lwjgl.glfw.GLFW.GLFW_KEY_SLASH
import org.lwjgl.glfw.GLFW.GLFW_KEY_SPACE
import org.lwjgl.glfw.GLFW.GLFW_KEY_T
import org.lwjgl.glfw.GLFW.GLFW_KEY_TAB
import org.lwjgl.glfw.GLFW.GLFW_KEY_U
import org.lwjgl.glfw.GLFW.GLFW_KEY_UP
import org.lwjgl.glfw.GLFW.GLFW_KEY_V
import org.lwjgl.glfw.GLFW.GLFW_KEY_W
import org.lwjgl.glfw.GLFW.GLFW_KEY_WORLD_1
import org.lwjgl.glfw.GLFW.GLFW_KEY_WORLD_2
import org.lwjgl.glfw.GLFW.GLFW_KEY_X
import org.lwjgl.glfw.GLFW.GLFW_KEY_Y
import org.lwjgl.glfw.GLFW.GLFW_KEY_Z

@Suppress("unused")
enum class Key(
    val code: Int,
    val printable: Boolean,
) {

    SPACE(GLFW_KEY_SPACE, true),
    APOSTROPHE(GLFW_KEY_APOSTROPHE, true),
    COMMA(GLFW_KEY_COMMA, true),
    MINUS(GLFW_KEY_MINUS, true),
    PERIOD(GLFW_KEY_PERIOD, true),
    SLASH(GLFW_KEY_SLASH, true),
    NUM_0(GLFW_KEY_0, true),
    NUM_1(GLFW_KEY_1, true),
    NUM_2(GLFW_KEY_2, true),
    NUM_3(GLFW_KEY_3, true),
    NUM_4(GLFW_KEY_4, true),
    NUM_5(GLFW_KEY_5, true),
    NUM_6(GLFW_KEY_6, true),
    NUM_7(GLFW_KEY_7, true),
    NUM_8(GLFW_KEY_8, true),
    NUM_9(GLFW_KEY_9, true),
    SEMICOLON(GLFW_KEY_SEMICOLON, true),
    EQUAL(GLFW_KEY_EQUAL, true),
    A(GLFW_KEY_A, true),
    B(GLFW_KEY_B, true),
    C(GLFW_KEY_C, true),
    D(GLFW_KEY_D, true),
    E(GLFW_KEY_E, true),
    F(GLFW_KEY_F, true),
    G(GLFW_KEY_G, true),
    H(GLFW_KEY_H, true),
    I(GLFW_KEY_I, true),
    J(GLFW_KEY_J, true),
    K(GLFW_KEY_K, true),
    L(GLFW_KEY_L, true),
    M(GLFW_KEY_M, true),
    N(GLFW_KEY_N, true),
    O(GLFW_KEY_O, true),
    P(GLFW_KEY_P, true),
    Q(GLFW_KEY_Q, true),
    R(GLFW_KEY_R, true),
    S(GLFW_KEY_S, true),
    T(GLFW_KEY_T, true),
    U(GLFW_KEY_U, true),
    V(GLFW_KEY_V, true),
    W(GLFW_KEY_W, true),
    X(GLFW_KEY_X, true),
    Y(GLFW_KEY_Y, true),
    Z(GLFW_KEY_Z, true),
    LEFT_BRACKET(GLFW_KEY_LEFT_BRACKET, true),
    BACKSLASH(GLFW_KEY_BACKSLASH, true),
    RIGHT_BRACKET(GLFW_KEY_RIGHT_BRACKET, true),
    GRAVE_ACCENT(GLFW_KEY_GRAVE_ACCENT, true),
    WORLD_1(GLFW_KEY_WORLD_1, true),
    WORLD_2(GLFW_KEY_WORLD_2, true),

    ESCAPE(GLFW_KEY_ESCAPE, false),
    ENTER(GLFW_KEY_ENTER, false),
    TAB(GLFW_KEY_TAB, false),
    BACKSPACE(GLFW_KEY_BACKSPACE, false),
    INSERT(GLFW_KEY_INSERT, false),
    DELETE(GLFW_KEY_DELETE, false),
    RIGHT(GLFW_KEY_RIGHT, false),
    LEFT(GLFW_KEY_LEFT, false),
    DOWN(GLFW_KEY_DOWN, false),
    UP(GLFW_KEY_UP, false),
    PAGE_UP(GLFW_KEY_PAGE_UP, false),
    PAGE_DOWN(GLFW_KEY_PAGE_DOWN, false),
    HOME(GLFW_KEY_HOME, false),
    END(GLFW_KEY_END, false),
    CAPS_LOCK(GLFW_KEY_CAPS_LOCK, false),
    SCROLL_LOCK(GLFW_KEY_SCROLL_LOCK, false),
    NUM_LOCK(GLFW_KEY_NUM_LOCK, false),
    PRINT_SCREEN(GLFW_KEY_PRINT_SCREEN, false),
    PAUSE(GLFW_KEY_PAUSE, false),
    F1(GLFW_KEY_F1, false),
    F2(GLFW_KEY_F2, false),
    F3(GLFW_KEY_F3, false),
    F4(GLFW_KEY_F4, false),
    F5(GLFW_KEY_F5, false),
    F6(GLFW_KEY_F6, false),
    F7(GLFW_KEY_F7, false),
    F8(GLFW_KEY_F8, false),
    F9(GLFW_KEY_F9, false),
    F10(GLFW_KEY_F10, false),
    F11(GLFW_KEY_F11, false),
    F12(GLFW_KEY_F12, false),
    F13(GLFW_KEY_F13, false),
    F14(GLFW_KEY_F14, false),
    F15(GLFW_KEY_F15, false),
    F16(GLFW_KEY_F16, false),
    F17(GLFW_KEY_F17, false),
    F18(GLFW_KEY_F18, false),
    F19(GLFW_KEY_F19, false),
    F20(GLFW_KEY_F20, false),
    F21(GLFW_KEY_F21, false),
    F22(GLFW_KEY_F22, false),
    F23(GLFW_KEY_F23, false),
    F24(GLFW_KEY_F24, false),
    F25(GLFW_KEY_F25, false),
    KP_0(GLFW_KEY_KP_0, false),
    KP_1(GLFW_KEY_KP_1, false),
    KP_2(GLFW_KEY_KP_2, false),
    KP_3(GLFW_KEY_KP_3, false),
    KP_4(GLFW_KEY_KP_4, false),
    KP_5(GLFW_KEY_KP_5, false),
    KP_6(GLFW_KEY_KP_6, false),
    KP_7(GLFW_KEY_KP_7, false),
    KP_8(GLFW_KEY_KP_8, false),
    KP_9(GLFW_KEY_KP_9, false),
    KP_DECIMAL(GLFW_KEY_KP_DECIMAL, false),
    KP_DIVIDE(GLFW_KEY_KP_DIVIDE, false),
    KP_MULTIPLY(GLFW_KEY_KP_MULTIPLY, false),
    KP_SUBTRACT(GLFW_KEY_KP_SUBTRACT, false),
    KP_ADD(GLFW_KEY_KP_ADD, false),
    KP_ENTER(GLFW_KEY_KP_ENTER, false),
    KP_EQUAL(GLFW_KEY_KP_EQUAL, false),
    LEFT_SHIFT(GLFW_KEY_LEFT_SHIFT, false),
    LEFT_CONTROL(GLFW_KEY_LEFT_CONTROL, false),
    LEFT_ALT(GLFW_KEY_LEFT_ALT, false),
    LEFT_SUPER(GLFW_KEY_LEFT_SUPER, false),
    RIGHT_SHIFT(GLFW_KEY_RIGHT_SHIFT, false),
    RIGHT_CONTROL(GLFW_KEY_RIGHT_CONTROL, false),
    RIGHT_ALT(GLFW_KEY_RIGHT_ALT, false),
    RIGHT_SUPER(GLFW_KEY_RIGHT_SUPER, false),
    MENU(GLFW_KEY_MENU, false),
}
